---
title: 'Reinventing an airline from a-to-z. A design:success case story'
timezone: UTC
email: success@designsuccess.com
description: 'design:success case story: Reinventing Mexico’s national airline from A-
to-Z. Growing loyalty from 54% to 88%! The sky has no limits.'
og_image: '/assets/img/og_image.jpg'
keywords: 'design:success case story: Reinventing Mexico’s national airline from A-to-Z. Growing loyalty from 54% to 88%! The sky has no limits.'
url: http://designsuccess.com/mexicana
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- webpack
sass:
  style: compressed
github:
- metadata
