---
title: 'mexicana'
timezone: UTC
email: success@designsuccess.com
description: Mexicana
og_image: "/assets/img/og_image.jpg"
baseurl: 
url: http://mexicana.designsuccess.com
markdown: kramdown
plugins:
- jekyll-feed
- octopress-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- webpack
sass:
  style: compressed
github:
- metadata
